name: "Irene HA Addon"
version: "1.0.2"
slug: "irene_ha_addon"
description: "Запускает приложение Irene, загружая его исходный код"
arch:
  - amd64
  - aarch64
startup: application
boot: auto
init: false
webui: https://[HOST]:[PORT:5003]
ports:
  5003/tcp: 5003
homeassistant_api: true 
options:
  log_level: "info"
  irene_branch: "master"
schema:
  log_level: "list(debug|info|warning|error|fatal)"
  irene_branch: "str"
map:
  - config:rw